name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to VPS via SSH
    runs-on: ubuntu-latest

    # Le déploiement ne se fera que si tous les autres jobs (lint/tests) sont verts
    # Si tu veux qu'il s’exécute toujours, supprime "needs"
    # needs: [cs-check, tests]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo '✅ Connexion SSH réussie !'"

      - name: Deploy files with rsync
        run: |
          rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no" \
            ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/david/test-ci/

      - name: Run post-deploy composer install
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            cd /home/david/test-ci &&
            composer install --no-dev --optimize-autoloader
          "
